import = [
    "~/.config/alacritty/nord.toml"
]

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Medium"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 100000

[window]
dynamic_title = true
opacity = 0.8

[window.dimensions]
columns = 125
lines = 25

[window.padding]
x = 4
y = 4
